// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.36.2
// source: pharmacy.proto

package pharmacypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PharmacyService_CheckDrugAvailability_FullMethodName    = "/medcore.pharmacy.v1.PharmacyService/CheckDrugAvailability"
	PharmacyService_ReservePrescriptionStock_FullMethodName = "/medcore.pharmacy.v1.PharmacyService/ReservePrescriptionStock"
)

// PharmacyServiceClient is the client API for PharmacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PharmacyServiceClient interface {
	CheckDrugAvailability(ctx context.Context, in *CheckDrugRequest, opts ...grpc.CallOption) (*CheckDrugResponse, error)
	ReservePrescriptionStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error)
}

type pharmacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPharmacyServiceClient(cc grpc.ClientConnInterface) PharmacyServiceClient {
	return &pharmacyServiceClient{cc}
}

func (c *pharmacyServiceClient) CheckDrugAvailability(ctx context.Context, in *CheckDrugRequest, opts ...grpc.CallOption) (*CheckDrugResponse, error) {
	out := new(CheckDrugResponse)
	err := c.cc.Invoke(ctx, PharmacyService_CheckDrugAvailability_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) ReservePrescriptionStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error) {
	out := new(ReserveStockResponse)
	err := c.cc.Invoke(ctx, PharmacyService_ReservePrescriptionStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PharmacyServiceServer is the server API for PharmacyService service.
// All implementations must embed UnimplementedPharmacyServiceServer
// for forward compatibility
type PharmacyServiceServer interface {
	CheckDrugAvailability(context.Context, *CheckDrugRequest) (*CheckDrugResponse, error)
	ReservePrescriptionStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error)
	mustEmbedUnimplementedPharmacyServiceServer()
}

// UnimplementedPharmacyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPharmacyServiceServer struct {
}

func (UnimplementedPharmacyServiceServer) CheckDrugAvailability(context.Context, *CheckDrugRequest) (*CheckDrugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDrugAvailability not implemented")
}
func (UnimplementedPharmacyServiceServer) ReservePrescriptionStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReservePrescriptionStock not implemented")
}
func (UnimplementedPharmacyServiceServer) mustEmbedUnimplementedPharmacyServiceServer() {}

// UnsafePharmacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PharmacyServiceServer will
// result in compilation errors.
type UnsafePharmacyServiceServer interface {
	mustEmbedUnimplementedPharmacyServiceServer()
}

func RegisterPharmacyServiceServer(s grpc.ServiceRegistrar, srv PharmacyServiceServer) {
	s.RegisterService(&PharmacyService_ServiceDesc, srv)
}

func _PharmacyService_CheckDrugAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).CheckDrugAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_CheckDrugAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).CheckDrugAvailability(ctx, req.(*CheckDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_ReservePrescriptionStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).ReservePrescriptionStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_ReservePrescriptionStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).ReservePrescriptionStock(ctx, req.(*ReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PharmacyService_ServiceDesc is the grpc.ServiceDesc for PharmacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PharmacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medcore.pharmacy.v1.PharmacyService",
	HandlerType: (*PharmacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDrugAvailability",
			Handler:    _PharmacyService_CheckDrugAvailability_Handler,
		},
		{
			MethodName: "ReservePrescriptionStock",
			Handler:    _PharmacyService_ReservePrescriptionStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pharmacy.proto",
}
